namespace HDFC.PDFCoordinateMapper.Api.Models
{
    public sealed class CommonApprovalArRequest
    {
        public string Qflag { get; set; }
        public string Auto_Id { get; set; }
        public string tbl_Auto_Id { get; set; }
        public string MasterName { get; set; }
        public string User { get; set; }
        public string Group_Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Action { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public string CreatedDate { get; set; }
        public string RoleDescription { get; set; }
        public string RoleName { get; set; }
        public string ModifiedDate { get; set; }
        public string Password { get; set; }
        public string clienttype { get; set; }
        public string accounttype { get; set; }
        public string clientname { get; set; }
        public string clientid { get; set; }
        public string configuration { get; set; }
        public string specification { get; set; }
        public string Value { get; set; }
        public string isactive { get; set; }
    }

    public sealed class CommonApprovalRequest
    {
        public string Qflag { get; set; }
        public string Auto_Id { get; set; }
        public string tbl_Auto_Id { get; set; }
        public string MasterName { get; set; }
        public string User { get; set; }
        public string Group_Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Action { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public string CreatedDate { get; set; }
        public string RoleDescription { get; set; }
        public string RoleName { get; set; }
        public string ModifiedDate { get; set; }
        public string Password { get; set; }
        public string clienttype { get; set; }
        public string accounttype { get; set; }
        public string clientname { get; set; }
        public string clientid { get; set; }
        public string configuration { get; set; }
        public string specification { get; set; }
        public string Value { get; set; }
        public string isactive { get; set; }
        public string RejectRemark { get; set; }
        public string MATERIALCHANGE { get; set; }
        public string DATE_OF_REPORTING_SEBI { get; set; }
        public string fpi_grouping { get; set; }
        public string Active { get; set; }
        public string Auth_MasterName { get; set; }
        public string Auth_UpdatedBy { get; set; }
        public string Auth_CurrUser { get; set; }
        public string Auth_AutoId { get; set; }
        public string Auth_Mst_Id { get; set; }
        public string Auth_Action { get; set; }
        public string Auth_AppRejAction { get; set; }
        public string ROLE_Name { get; set; }
        public string ROLE_Description { get; set; }
        public string USER_Name { get; set; }
        public string USER_Password { get; set; }
        public string USER_Email { get; set; }
        public string USER_GroupId { get; set; }
        public string USER_ModifiedDate { get; set; }
        public string CLIENT_Type { get; set; }
        public string CLIENT_AccountType { get; set; }
        public string CLIENT_Name { get; set; }
        public string CLIENT_ID { get; set; }
        public string CATEGORY_TYPE { get; set; }
        public string AMOUNT_OF_USD { get; set; }
        public string SEBISUBCATEGORY_TYPE { get; set; }
        public string INTERNALSUBTYPE { get; set; }
        public string CONFIGURATION_Type { get; set; }
        public string CONFIGURATION_SPEC_Type { get; set; }
        public string CONFIGURATION_Value { get; set; }
        public string APPLICATION_Type { get; set; }
        public string IsPostreview { get; set; }
        public string APPLICATIONFOR { get; set; }
        public string EXHIBIT { get; set; }
        public string ISSUEDATE { get; set; }
        public string SERIALNUMBER { get; set; }
        public string SUBSEQ { get; set; }
        public string CATEGORY { get; set; }
        public string SUBCATEGORY { get; set; }
        public string DOCUMENTNAME { get; set; }
        public string ITEMSTOBCHECKED { get; set; }
        public string APPLICATION_TypeId { get; set; }
        public string APPLICATIONFORId { get; set; }
        public string CATEGORYId { get; set; }
        public string SUBCATEGORYId { get; set; }
        public string Name_of_Applicant { get; set; }
        public string GC_Name { get; set; }
        public string Application_Type { get; set; }
        public string Category_Type { get; set; }
        public string Sub_Category { get; set; }
        public string Internal_subtype { get; set; }
        public string Application_Date { get; set; }
        public string Date_Acknowledgement { get; set; }
        public string FeeRecdDate { get; set; }
        public string Application_Receipt_Date { get; set; }
        public string Date_of_Disposal { get; set; }
        public string FeePaidToSEBI { get; set; }
        public string Deferral_expiry_date { get; set; }
        public string Registration_Validity_Date { get; set; }
        public string Expiry_of_Registration { get; set; }
        public string DT_FINAL_DOCUMENTS { get; set; }
        public string Regn_Dt_Tobe_Completed { get; set; }
        public string SEBI_status { get; set; }
        public string FPI_Registration_No { get; set; }
        public string deferred_document { get; set; }
        public string Transition { get; set; }
        public string OutwardCustodianName { get; set; }
        public string Amount_of_Fees { get; set; }
        public string PaymentRefNo { get; set; }
        public string name_of_ubo { get; set; }
        public string application_for { get; set; }
        public string MiscApplnAsPerSebi { get; set; }
        public string select_option { get; set; }
        public string select_bank { get; set; }
        public string Foreign_Investor_Grouping { get; set; }
        public string NRI_conditonal { get; set; }
        public string MF_only_registration { get; set; }
        public string Conditional_registration { get; set; }
        public string Tracking_for_banker_certificate { get; set; }
        public string FPI_Ref_No { get; set; }
        public string Remarks { get; set; }
        public string isFreeze { get; set; }
        public string isLock_bit { get; set; }
        public string User_Unlock_By { get; set; }
        public string User_Unlock_Date { get; set; }
        public string User_Unlock_Comment { get; set; }
        public string User_Locked_entry { get; set; }
        public string User_Freezed_entry { get; set; }
        public string is_Post_Registration { get; set; }
        public string User_Post_Registration_entry { get; set; }
        public string FII_SA_FPI { get; set; }
        public string FII_SA_FPI_Reg_No { get; set; }
        public string EOPS_Transaction_Ref_No { get; set; }
        public string CheckerComment { get; set; }
        public string isReject { get; set; }
        public string RejectBy { get; set; }
        public string Pan { get; set; }
        public string PanStatus { get; set; }
        public string PanUpdatedBy { get; set; }
        public string PanUpdatedDate { get; set; }
        public string InvMgrName { get; set; }
        public string InvMgrRegNo { get; set; }
        public string FPI_Reg_Country { get; set; }
        public string NSDL_PAN_Fees { get; set; }
        public string Date_effective_change { get; set; }
        public string Date_of_intimation_to_DDP { get; set; }
        public string Date_of_intimation_to_SEBI_by_DDP { get; set; }
        public string Date_of_Intimation_to_NSDL_for_grouping { get; set; }
        public string Next_Annual_KYC_due_date { get; set; }
    }
}
