-- PDF Coordinate Mapper module sequences and triggers.
--
-- Purpose:
--   Generate AUTOID / LOGID values for MF_* tables.
--
-- Verified gap:
--   MF_* primary key columns are not identity columns and currently have no
--   MF_* sequences/triggers. Stored procedures should be able to insert rows
--   without manually calculating primary keys.
--
-- Style:
--   Matches existing Admin pattern:
--     USER_MASTER_APPROVAL_SEQ_TR
--     USER_MASTER_LOG_SEQ_TR
--     ROLE_MASTER_APPROVAL_SEQ_TR
--
-- Run as:
--   SYSTEM on service HDFCPDFMAP

SET DEFINE OFF;

PROMPT Creating PDF module sequences when missing...

DECLARE
  PROCEDURE create_sequence_if_missing(
    p_sequence_name IN VARCHAR2,
    p_table_name    IN VARCHAR2,
    p_column_name   IN VARCHAR2
  ) IS
    v_count NUMBER;
    v_start_with NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_sequences
     WHERE sequence_name = UPPER(p_sequence_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE
        'SELECT NVL(MAX(' || p_column_name || '), 0) + 1 FROM ' || p_table_name
        INTO v_start_with;

      EXECUTE IMMEDIATE
        'CREATE SEQUENCE ' || p_sequence_name ||
        ' MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH ' ||
        GREATEST(v_start_with, 1) ||
        ' NOCACHE NOCYCLE';
    END IF;
  END;
BEGIN
  create_sequence_if_missing('MF_AMC_MASTER_SEQ', 'MF_AMC_MASTER', 'AUTOID');
  create_sequence_if_missing('MF_AMC_MASTER_APP_SEQ', 'MF_AMC_MASTER_APP', 'AUTOID');
  create_sequence_if_missing('MF_AMC_MASTER_LOG_SEQ', 'MF_AMC_MASTER_LOG', 'LOGID');

  create_sequence_if_missing('MF_TEMPLATE_MASTER_SEQ', 'MF_TEMPLATE_MASTER', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MASTER_APP_SEQ', 'MF_TEMPLATE_MASTER_APP', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MASTER_LOG_SEQ', 'MF_TEMPLATE_MASTER_LOG', 'LOGID');

  create_sequence_if_missing('MF_TEMPLATE_MAPPING_MAIN_SEQ', 'MF_TEMPLATE_MAPPING_MAIN', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MAPPING_MAIN_APP_SEQ', 'MF_TEMPLATE_MAPPING_MAIN_APP', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MAPPING_MAIN_LOG_SEQ', 'MF_TEMPLATE_MAPPING_MAIN_LOG', 'LOGID');

  create_sequence_if_missing('MF_TEMPLATE_MAPPING_FIELD_SEQ', 'MF_TEMPLATE_MAPPING_FIELD', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MAPPING_FIELD_APP_SEQ', 'MF_TEMPLATE_MAPPING_FIELD_APP', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MAPPING_FIELD_LOG_SEQ', 'MF_TEMPLATE_MAPPING_FIELD_LOG', 'LOGID');

  create_sequence_if_missing('MF_TEMPLATE_MAPPING_FIELD_CONFIG_SEQ', 'MF_TEMPLATE_MAPPING_FIELD_CONFIG', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MAPPING_FIELD_CONFIG_APP_SEQ', 'MF_TEMPLATE_MAPPING_FIELD_CONFIG_APP', 'AUTOID');
  create_sequence_if_missing('MF_TEMPLATE_MAPPING_FIELD_CONFIG_LOG_SEQ', 'MF_TEMPLATE_MAPPING_FIELD_CONFIG_LOG', 'LOGID');

  create_sequence_if_missing('MF_PDF_PROCESS_STATUS_MASTER_SEQ', 'MF_PDF_PROCESS_STATUS_MASTER', 'AUTOID');
  create_sequence_if_missing('MF_PDF_PROCESS_BATCH_SEQ', 'MF_PDF_PROCESS_BATCH', 'AUTOID');
  create_sequence_if_missing('MF_PDF_PROCESS_ROW_SEQ', 'MF_PDF_PROCESS_ROW', 'AUTOID');
  create_sequence_if_missing('MF_PDF_PROCESS_VALIDATION_ERROR_SEQ', 'MF_PDF_PROCESS_VALIDATION_ERROR', 'AUTOID');
  create_sequence_if_missing('MF_PDF_GENERATED_DOCUMENT_SEQ', 'MF_PDF_GENERATED_DOCUMENT', 'AUTOID');
  create_sequence_if_missing('MF_PDF_PROCESS_BATCH_LOG_SEQ', 'MF_PDF_PROCESS_BATCH_LOG', 'AUTOID');
  create_sequence_if_missing('MF_PDF_PROCESS_ROW_LOG_SEQ', 'MF_PDF_PROCESS_ROW_LOG', 'AUTOID');
END;
/

PROMPT Creating PDF module triggers...

CREATE OR REPLACE TRIGGER MF_AMC_MASTER_SEQ_TR
BEFORE INSERT ON MF_AMC_MASTER
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_AMC_MASTER_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_AMC_MASTER_APP_SEQ_TR
BEFORE INSERT ON MF_AMC_MASTER_APP
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_AMC_MASTER_APP_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_AMC_MASTER_LOG_SEQ_TR
BEFORE INSERT ON MF_AMC_MASTER_LOG
FOR EACH ROW
WHEN (NEW.LOGID IS NULL)
BEGIN
  SELECT MF_AMC_MASTER_LOG_SEQ.NEXTVAL INTO :NEW.LOGID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MASTER_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MASTER
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MASTER_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MASTER_APP_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MASTER_APP
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MASTER_APP_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MASTER_LOG_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MASTER_LOG
FOR EACH ROW
WHEN (NEW.LOGID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MASTER_LOG_SEQ.NEXTVAL INTO :NEW.LOGID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_MAIN_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_MAIN
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_MAIN_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_MAIN_APP_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_MAIN_APP
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_MAIN_APP_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_MAIN_LOG_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_MAIN_LOG
FOR EACH ROW
WHEN (NEW.LOGID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_MAIN_LOG_SEQ.NEXTVAL INTO :NEW.LOGID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_FIELD_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_FIELD
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_FIELD_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_FIELD_APP_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_FIELD_APP
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_FIELD_APP_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_FIELD_LOG_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_FIELD_LOG
FOR EACH ROW
WHEN (NEW.LOGID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_FIELD_LOG_SEQ.NEXTVAL INTO :NEW.LOGID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_FIELD_CONFIG_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_FIELD_CONFIG
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_FIELD_CONFIG_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_FIELD_CONFIG_APP_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_FIELD_CONFIG_APP
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_FIELD_CONFIG_APP_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_TEMPLATE_MAPPING_FIELD_CONFIG_LOG_SEQ_TR
BEFORE INSERT ON MF_TEMPLATE_MAPPING_FIELD_CONFIG_LOG
FOR EACH ROW
WHEN (NEW.LOGID IS NULL)
BEGIN
  SELECT MF_TEMPLATE_MAPPING_FIELD_CONFIG_LOG_SEQ.NEXTVAL INTO :NEW.LOGID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_PDF_PROCESS_STATUS_MASTER_SEQ_TR
BEFORE INSERT ON MF_PDF_PROCESS_STATUS_MASTER
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_PDF_PROCESS_STATUS_MASTER_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_PDF_PROCESS_BATCH_SEQ_TR
BEFORE INSERT ON MF_PDF_PROCESS_BATCH
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_PDF_PROCESS_BATCH_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_PDF_PROCESS_ROW_SEQ_TR
BEFORE INSERT ON MF_PDF_PROCESS_ROW
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_PDF_PROCESS_ROW_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_PDF_PROCESS_VALIDATION_ERROR_SEQ_TR
BEFORE INSERT ON MF_PDF_PROCESS_VALIDATION_ERROR
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_PDF_PROCESS_VALIDATION_ERROR_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_PDF_GENERATED_DOCUMENT_SEQ_TR
BEFORE INSERT ON MF_PDF_GENERATED_DOCUMENT
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_PDF_GENERATED_DOCUMENT_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_PDF_PROCESS_BATCH_LOG_SEQ_TR
BEFORE INSERT ON MF_PDF_PROCESS_BATCH_LOG
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_PDF_PROCESS_BATCH_LOG_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER MF_PDF_PROCESS_ROW_LOG_SEQ_TR
BEFORE INSERT ON MF_PDF_PROCESS_ROW_LOG
FOR EACH ROW
WHEN (NEW.AUTOID IS NULL)
BEGIN
  SELECT MF_PDF_PROCESS_ROW_LOG_SEQ.NEXTVAL INTO :NEW.AUTOID FROM DUAL;
END;
/

PROMPT Verifying PDF module sequences...

SELECT sequence_name
  FROM user_sequences
 WHERE sequence_name LIKE 'MF_%'
 ORDER BY sequence_name;

PROMPT Verifying PDF module triggers...

SELECT trigger_name, table_name, status
  FROM user_triggers
 WHERE trigger_name LIKE 'MF_%_SEQ_TR'
 ORDER BY table_name, trigger_name;

PROMPT PDF module sequences and triggers script completed.
